version: '3.3'
services:
  openrestyt:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    #privileged: true
    ports:
      - "8080:80"
      - "4443:443"
    #command: /bin/sh -c "while true;do sleep 100;done"
    #command: /bin/sh -c "source /etc/profile && nginx -c /usr/local/openresty/nginx/conf/nginx.conf && nginx -g \"daemon off;\""
    command: /bin/sh -c "source /etc/profile && nginx -g \"daemon off;\""
    #command: 
    # - /bin/sh
    #  - -c 
    #  - |
    #    nginx -c /usr/local/openresty/nginx/conf/nginx.conf
    #     nginx -g "daemon off;":