from centos

COPY ./start.sh /

COPY openresty-1.13.6.1 /home/openresty-1.13.6.1

RUN yum -y install readline-devel pcre pcre-devel openssl openssl-devel gcc curl GeoIP-devel wget

RUN cd /home/openresty-1.13.6.1 && chmod +x  configure  && ./configure --with-luajit --with-pcre --with-http_gzip_static_module --with-http_realip_module --with-http_geoip_module --with-http_ssl_module  --with-http_stub_status_module \

&& make && make install

ENV NGINX_HOME=/usr/local/openresty/nginx

ENV PATH $NGINX_HOME/sbin:$PATH

RUN chmod +x /start.sh

ENTRYPOINT ["sh","/start.sh"]

EXPOSE 80

